import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer"
import localFont from "next/font/local";

const miFuente = localFont({
  src: [
    {
      path: "./fonts/ppmondwest-regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/ppneuebit-bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--fuente-personalizada", // opcional si usarás como variable CSS
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Apix Trade",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={miFuente.variable}>
      <body
        className={`${miFuente.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* CAPA SUPERIOR */}
        <div className="relative z-10">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
